

HP_BAR_WIDTH = 30
HP_BAR_HEIGHT = 3


SCREEN_HEIGHT  = 600
SCREEN_WIDTH = 960
SCREEN_TITLE = "LAST MAN STANDING"
# BACKGROUND_SCALING = 0.5

# How many pixels to keep as a minimum margin between the character
# and the edge of the screen.
VIEWPORT_MARGIN = 40
RIGHT_MARGIN = 150

CHARACTER_SCALE = 0.15
SPRITE_SCALING = 0.3
ZOMBIE_SCALE = 0.25
TILE_SIZE = 128
SCALED_TILE_SIZE = TILE_SIZE * SPRITE_SCALING
MAP_HEIGHT = 16
CHEST_SCALE = 0.5
# Physics
MOVEMENT_SPEED = 5
JUMP_SPEED = 14
GRAVITY = 0.5
FIRE_BLAST_SCALE = 0.85
FIRE_BLAST_SPEED = 6
SPEAR_SPEED = 3
# HERO_SCALING = 1
# SKELETON_SCALING = 0.3
SPEAR_SCALE = 0.5
ZOMBIE_COUNT = 10
ZOMBIE_SPEED = 0.5
DRAGON_SPEED = 0.8
DRAGON_SCALE = 0.8
# SKELETON_SPEED = 0.5

PLAYER_DAMAGE = 10

WALL_ID = 44

WIZARD_SCALE = 0.4

KNIGHT_SCALE = 0.7